name: Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node hello.js

  next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node hello.js
